-- AlterTable
ALTER TABLE "User" ADD COLUMN     "daily_api_calls" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "hourly_api_calls" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "last_daily_reset" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "last_hourly_reset" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "tier" TEXT NOT NULL DEFAULT 'free';
